# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 易企秀|免费H5页面移动微场景应用制作平台,场景定制设计师平台,场景推广平台,企业场景自营销管家(官网:www.eqxiu.com)
email: wangshijiang@eqxiu.com
description: 认真工作，享受生活
baseurl: "/" # the subpath of your site, e.g. /blog
url: “https://localhost:4000” # the base hostname & protocol for your site
repository: https://github.com/eqxiu/eqxiu.github.io
twitter_username: eqxiu
github_username:  eqxiu

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
exclude: [node_modules, gulpfile.js]

# Pagination
paginate: 7
paginate_path: "page/:num"

gems:
 - jekyll-paginate